{{/*
BabyNest API Service
Requirements: 15.2 (Kubernetes deployment with Helm charts)
*/}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "babynest.fullname" . }}-api
  labels:
    {{- include "babynest.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "babynest.api.selectorLabels" . | nindent 4 }}
