{{/*
BabyNest Service Account
Requirements: 15.2 (Kubernetes deployment with Helm charts)
*/}}
{{- if .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "babynest.serviceAccountName" . }}
  labels:
    {{- include "babynest.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
